DROP TABLE IF EXISTS EMPLOYEE;
 
CREATE TABLE EMPLOYEE (
  EMPLOYEE_ID INT AUTO_INCREMENT PRIMARY KEY,
  EMPLOYEE_NAME  VARCHAR(250) NOT NULL,
  TITLE VARCHAR(250) NOT NULL,
  BUSINESS_UNIT VARCHAR(250) DEFAULT NULL,
  PLACE VARCHAR(250) NOT NULL,
  SUPERVISOR_ID  VARCHAR(250) DEFAULT NULL,
  COMPETENCIES  VARCHAR(250) DEFAULT NULL,
  SALARY  NUMBER(11) NOT NULL
);
 
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, TITLE, PLACE,SALARY,COMPETENCIES) VALUES
  ('Kamatchi', 'Module Lead','Bangalore',10000,'CORE');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, TITLE, PLACE,SALARY,COMPETENCIES) VALUES
  ('Divya', 'Manager','Chennai',20000,'FUNCTIONAL');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, TITLE, PLACE,SALARY,COMPETENCIES) VALUES
  ('Nagaraj', 'Module Lead','Bangalore',30000,'CORE');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, TITLE, PLACE,SALARY,COMPETENCIES) VALUES
  ('Vijay', 'Pricipal SE','Mangalore',40000,'CORE FUNCTIONAL');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, TITLE, PLACE,SALARY,COMPETENCIES) VALUES
  ('Kumar', 'Business Analyst','Madurai',50000,'CORE');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, TITLE, PLACE,SALARY,COMPETENCIES) VALUES
  ('Prasanna', 'Module Lead','Bangalore',10000,'CORE FUNCTIONAL');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, TITLE, PLACE,SALARY,COMPETENCIES) VALUES
  ('Guna', 'Module Lead','Salem',60000,'FUNCTIONAL');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, TITLE, PLACE,SALARY,COMPETENCIES) VALUES
  ('Sekar', 'Module Lead','Coimbatore',60000,'CORE FUNCTIONAL');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, TITLE, PLACE,SALARY,COMPETENCIES) VALUES
  ('Ajay', 'Module Lead','Ooty',80000,'FUNCTIONAL');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, TITLE, PLACE,SALARY,COMPETENCIES) VALUES
  ('Kathir', 'Module Lead','Mysore',30000,'CORE FUNCTIONAL');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, TITLE, PLACE,SALARY,COMPETENCIES) VALUES
  ('Murugesh', 'Module Lead','Bangalore',2000,'CORE FUNCTIONAL');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, TITLE, PLACE,SALARY,COMPETENCIES) VALUES
  ('Bala', 'Module Lead','Chennai',15000,'CORE');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, TITLE, PLACE,SALARY,COMPETENCIES) VALUES
  ('Balaji', 'Module Lead','Chennai',150000,'CORE');

